### PR TITLE
Adding the microphone mute toggle icon and modifying `volumectl`

### PR DESCRIPTION
**Pull request by leophys**
Hi, thanks for your work!

I wanted to add the option to toggle the microphone mute. I also heavily modified the `volumectl` script. The main changes are:
 - I run it using `bash`
 - I am assuming that the user has `pulseaudio` running
 - I tried to stick to the current interface, but diverted a bit for the microphone case

I am open for discussion :)

### CODE REVIEW

**Comment by misterdanb** [comment]
This looks fine to me. I think by now most people should use pulseaudio. In case this turns out to be a problem, this can be revisited in a seperate issue.

**Comment by leophys** [comment]
Thanks for accepting the PR!

May I ask you to also create a tag and update the [AUR package](https://aur.archlinux.org/packages/avizo) (as I am a happy arch user too)?

Thanks again!

**Comment by misterdanb** [comment]
Bumped the version to the most recent commit.

**Comment by ErikReider** [comment]
the `_current` function doesn't work when running pulseaudio through pipewire. I'll try to fix it :)

**Comment by ErikReider** [comment]
Fixed in #14

**Pull request merged**
